---
platform: linux

image_resource:
  type: docker-image
  source: { repository: rust }

inputs:
  - name: source

params:
  target:

outputs:
  - name: binaries

run:
  dir: source
  path: sh
  args:
    - -c
    - |
      if [ "$target" == x86_64-pc-windows-gnu ] ; then
        apt --yes update
        apt --yes install gcc-mingw-w64
      fi

      rustup target add "$target"
      cargo build --release --target "$target"

      find target/"$target"/release/ -maxdepth 1 -type f -executable -exec cp {} ../binaries \;
