[package]
name = "rustomato-cli"
version = "0.0.6"
authors = ["Steffen Uhlig <steffen@familie-uhlig.net>"]
edition = "2018"

[[bin]]
name = "rustomato"
path = "src/main.rs"

[dependencies]
rustomato = { path = "../rustomato" }
clap = "3.0.0-beta.4"
url = "2.2.2"
dirs = "3.0.2"

